#!/bin/sh

# This will create a CYBOS (fat12) boot image. Mind that the sectors we need to
# load BOOTLVL2.BIN are hardcoded in BOOTLVL1.BIN. As soon as the actual bootalize
# program works, we can detect which sectors we need to load by looking in the
# FAT12 structure.
#

# Create zero filled 1MB image
dd if=/dev/zero of=../binary/image/fat12.img bs=1024 count=1024

# Format it to FAT12
mkdosfs -n CYBOS ../binary/image/fat12.img

# Add boot sector to start of image (we overwrite BPB!)
dd if=../binary/boot/bootlvl1.bin of=../binary/image/fat12.img bs=512 seek=0 conv=notrunc

# Mount image
if [ ! -d /tmp/fat12mnt ] ; then
  mkdir /tmp/fat12mnt
fi

sudo mount -o loop ../binary/image/fat12.img /tmp/fat12mnt

# Make items in image
mkdir /tmp/fat12mnt/SYSTEM
cp ../binary/boot/bootlvl1.bin /tmp/fat12mnt/SYSTEM/BOOTLVL1.BIN
cp ../binary/boot/bootlvl2.bin /tmp/fat12mnt/SYSTEM/BOOTLVL2.BIN
cp ../binary/kernel/cybos32.bin /tmp/fat12mnt/SYSTEM/CYBOS32.BIN
#cp ../binary/boot/apps/init.bin /tmp/fat12mnt/SYSTEM/INIT.BIN
#cp ../binary/boot/apps/test1.bin /tmp/fat12mnt/SYSTEM/TEST1.BIN
#cp ../binary/boot/apps/test2.bin /tmp/fat12mnt/SYSTEM/TEST2.BIN
#cp ../binary/boot/apps/test3.bin /tmp/fat12mnt/SYSTEM/TEST3.BIN
#cp ../binary/boot/apps/test4.bin /tmp/fat12mnt/SYSTEM/TEST4.BIN

# Unmount
umount /tmp/fat12mnt
